### ISSUE TITLE
Improvement of the generic document indexer

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/powerhouse#687] opened 2024-12-09 11:32 UTC

**Comment by froid1911** [comment] 2024-12-12 16:41
@CallmeT-ty duplicate of https://github.com/orgs/powerhouse-inc/projects/1/views/24?pane=issue&itemId=85409734&issue=powerhouse-inc%7Cpowerhouse%7C465 ?

**Closed as completed** 2024-12-12 16:41 UTC
